// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $index from "./routes/index.tsx";
import * as $login_index from "./routes/login/index.tsx";
import * as $part_create_index from "./routes/part/create/index.tsx";
import * as $part_index from "./routes/part/index.tsx";
import * as $vehicles_id_index from "./routes/vehicles/[id]/index.tsx";
import * as $vehicles_create_index from "./routes/vehicles/create/index.tsx";
import * as $vehicles_index from "./routes/vehicles/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $PartCreate from "./islands/PartCreate.tsx";
import * as $PartSearch from "./islands/PartSearch.tsx";
import * as $VehicleCreate from "./islands/VehicleCreate.tsx";
import * as $VehicleDetail from "./islands/VehicleDetail.tsx";
import * as $VehiclePartSearch from "./islands/VehiclePartSearch.tsx";
import * as $VehicleSearch from "./islands/VehicleSearch.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/index.tsx": $index,
    "./routes/login/index.tsx": $login_index,
    "./routes/part/create/index.tsx": $part_create_index,
    "./routes/part/index.tsx": $part_index,
    "./routes/vehicles/[id]/index.tsx": $vehicles_id_index,
    "./routes/vehicles/create/index.tsx": $vehicles_create_index,
    "./routes/vehicles/index.tsx": $vehicles_index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/PartCreate.tsx": $PartCreate,
    "./islands/PartSearch.tsx": $PartSearch,
    "./islands/VehicleCreate.tsx": $VehicleCreate,
    "./islands/VehicleDetail.tsx": $VehicleDetail,
    "./islands/VehiclePartSearch.tsx": $VehiclePartSearch,
    "./islands/VehicleSearch.tsx": $VehicleSearch,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
